Repository argon1025/TILog-server, pull requests merged in 2021-12, with the labels that each got.

#100 Til 86 에러 처리 개선
  src/src/ExceptionFilters/Errors/Validation/Validation.error.ts
  src/src/ExceptionFilters/HttpException.filter.ts
  src/src/main.ts
Labels: documentation⚡️기능개선

#101 Add Helmet module
  src/package-lock.json
  src/package.json
  src/src/main.ts
Labels: enhancement💻기능추가

#102 Add throttler, Redis storage
  src/package-lock.json
  src/package.json
  src/src/ExceptionFilters/HttpException.filter.ts
  src/src/app.module.ts
  src/src/categories/categories.controller.ts
Labels: documentation⚡️기능개선, enhancement💻기능추가

#103 CORS 환경변수, README 수정
  README.md
  src/src/main.ts
Labels: bug🛠버그, documentation⚡️기능개선

#105 class-validator 적용
  src/src/comments/comments.controller.ts
  src/src/comments/comments.service.ts
  src/src/comments/dto/controller/commentContent.dto.ts
  src/src/comments/dto/controller/createCommentBody.dto.ts
  src/src/comments/dto/controller/createReplyBody.dto.ts
  src/src/comments/dto/controller/updateCommentBody.dto.ts
  src/src/comments/dto/getComments.dto.ts
  src/src/comments/dto/getReplies.dto.ts
  src/src/comments/dto/getReply.dto.ts
  src/src/user-blog-customization/user-blog-customization.controller.ts
  src/src/user-blog-customization/user-blog-customization.service.ts
Labels: documentation⚡️기능개선

#106 Auth Guard Error handling
  src/src/ExceptionFilters/Errors/Auth/Auth.error.ts
  src/src/auth/guard/auth.guard.ts
Labels: documentation⚡️기능개선

#107 Til 165 CICD 적용 및 오류 수정
  .circleci/config.yml
  .circleci/scripts/envSettings.txt
  .circleci/scripts/generate-env-files.sh
  src/src/comments/dto/restoreDeletedComment.dto.ts
Labels: enhancement💻기능추가

#108 Fix 워크플로우 정규식 오류 수정
  .circleci/config.yml
Labels: bug🛠버그

#109 Fix 쉘 스크립트 권한 수정 및 릴리즈
  .circleci/scripts/generate-env-files.sh
Labels: duplicate/중복

#121 HotFix 이후 소스코드 클린업
  src/Dockerfile
  src/src/main.ts
Labels: documentation⚡️기능개선

#123 Til 168
  src/src/app.module.ts
  src/src/comments/comments.controller.ts
  src/src/comments/dto/controller/updateCommentBody.dto.ts
  src/src/main.ts
  src/src/users/users.controller.ts
  src/src/users/users.service.ts
Labels: documentation⚡️기능개선

#130 TIL-129 복구 실패 및 getcomment시 삭제된 comment도 호출하도록 변경
  src/src/ExceptionFilters/Errors/Comments/Comment.error.ts
  src/src/comments/comments.service.ts
Labels: bug🛠버그, documentation⚡️기능개선

#131 리팩터링 포스트 서비스
  src/src/posts/dto/Services/GetPostDetail.DTO.ts
  src/src/posts/dto/Services/GetPostWriter.DTO.ts
  src/src/posts/posts.controller.ts
  src/src/posts/posts.service.ts
  src/src/repositories/PostLikes.repository.ts
  src/src/repositories/postViews.repository.ts
  src/src/repositories/posts.repository.ts
Labels: documentation⚡️기능개선, enhancement💻기능추가
