Repository argon1025/TILog-server, pull requests merged in 2021-11, with the labels that each got.

#60 Post.service를 리팩터링 하라
  src/src/ExceptionFilters/Errors/ErrorHandlerNotFound.error.ts
  src/src/ExceptionFilters/Errors/Posts/Post.error.ts
  src/src/posts/dto/Services/AddPostViewCount.DTO.ts
  src/src/posts/dto/Services/CreatePost.DTO.ts
  src/src/posts/dto/Services/GetPostDetail.DTO.ts
  src/src/posts/dto/Services/GetPostWriter.DTO.ts
  src/src/posts/dto/Services/GetPosts.DTO.ts
  src/src/posts/dto/Services/SoftDeletePost.DTO.ts
  src/src/posts/dto/Services/UpdatePost.DTO.ts
  src/src/posts/posts.controller.ts
  src/src/posts/posts.service.spec.ts
  src/src/posts/posts.service.ts
  src/src/utilities/time.utility.ts
Labels: bug🛠버그, documentation⚡️기능개선, enhancement💻기능추가

#61 Til 82 PostService.PostLike 구현
  src/src/ExceptionFilters/Errors/Posts/Post.error.ts
  src/src/posts/dto/Services/SetPostToDislike.DTO.ts
  src/src/posts/dto/Services/SetPostToLike.DTO.ts
  src/src/posts/posts.service.ts
Labels: documentation⚡️기능개선, enhancement💻기능추가

#63 Til 81 Swaager를 추가하라
  src/package.json
  src/src/entities/PostLike.ts
  src/src/entities/PostView.ts
  src/src/entities/Posts.ts
  src/src/main.ts
  src/src/posts/dto/Services/AddPostViewCount.DTO.ts
  src/src/posts/dto/Services/CreatePost.DTO.ts
  src/src/posts/dto/Services/GetPostDetail.DTO.ts
  src/src/posts/dto/Services/GetPostWriter.DTO.ts
  src/src/posts/dto/Services/GetPosts.DTO.ts
  src/src/posts/dto/Services/SetPostToDislike.DTO.ts
  src/src/posts/dto/Services/SetPostToLike.DTO.ts
  src/src/posts/dto/Services/SoftDeletePost.DTO.ts
  src/src/posts/dto/Services/UpdatePost.DTO.ts
Labels: documentation⚡️기능개선, enhancement💻기능추가

#64 Comments Service
  src/src/comments/comments.module.ts
  src/src/comments/comments.service.ts
  src/src/comments/dto/service/writePostComments.dto.ts
  src/src/comments/dto/service/writeReplyComment.dto.ts
Labels: enhancement💻기능추가

#67 Til 83 Add File-upload resource
  src/package.json
  src/src/ExceptionFilters/Errors/FileUploads/FileUpload.error.ts
  src/src/app.module.ts
  src/src/file-uploads/dto/service/ImageFileUpload.DTO.ts
  src/src/file-uploads/dto/service/S3FileDelete.DTO.ts
  src/src/file-uploads/dto/service/s3FileUpload.DTO.ts
  src/src/file-uploads/file-uploads.controller.spec.ts
  src/src/file-uploads/file-uploads.controller.ts
  src/src/file-uploads/file-uploads.module.ts
  src/src/file-uploads/file-uploads.service.spec.ts
  src/src/file-uploads/file-uploads.service.ts
Labels: enhancement💻기능추가

#70 user-blog-customization
  src/src/app.module.ts
  src/src/user-blog-customization/dto/create-user-blog-customization.dto.ts
  src/src/user-blog-customization/dto/update-user-blog-customization.dto.ts
  src/src/user-blog-customization/user-blog-customization.controller.spec.ts
  src/src/user-blog-customization/user-blog-customization.controller.ts
  src/src/user-blog-customization/user-blog-customization.module.ts
  src/src/user-blog-customization/user-blog-customization.service.spec.ts
  src/src/user-blog-customization/user-blog-customization.service.ts
Labels: enhancement💻기능추가

#69 Comment unDelete service, controller 작성
  src/src/ExceptionFilters/Errors/Comments/Comment.error.ts
  src/src/comments/comments.controller.ts
  src/src/comments/comments.service.ts
  src/src/comments/dto/service/unDeleteComment.dto.ts
Labels: enhancement💻기능추가

#71 create UserBlogCustomization
  src/src/ExceptionFilters/Errors/UserBlogCustomization/UserBlogCustomization.Error.ts
  src/src/user-blog-customization/dto/create-user-blog-customization.dto.ts
  src/src/user-blog-customization/user-blog-customization.controller.ts
  src/src/user-blog-customization/user-blog-customization.module.ts
  src/src/user-blog-customization/user-blog-customization.service.ts
Labels: enhancement💻기능추가

#73 Til 80 Post 엔드포인트 구현
  src/src/posts/dto/Controller/Create.Posts.controller.DTO.ts
  src/src/posts/dto/Controller/Update.Posts.controller.DTO copy.ts
  src/src/posts/dto/Services/GetPosts.DTO.ts
  src/src/posts/posts.controller.ts
  src/src/posts/posts.service.ts
  src/src/utilities/Response.utility.ts
Labels: enhancement💻기능추가

#74 update service 구현
  src/src/ExceptionFilters/Errors/UserBlogCustomization/UserBlogCustomization.Error.ts
  src/src/user-blog-customization/user-blog-customization.controller.ts
  src/src/user-blog-customization/user-blog-customization.service.ts
Labels: enhancement💻기능추가

#75 Add fileUpload 엔드포인트 구현
  src/src/ExceptionFilters/Errors/FileUploads/FileUpload.error.ts
  src/src/file-uploads/file-uploads.controller.ts
Labels: enhancement💻기능추가

#76 Add Posts service Swagger Document
  src/src/posts/posts.controller.ts
Labels: documentation⚡️기능개선, enhancement💻기능추가

#77 Add fileUpload Swagger Document
  src/src/file-uploads/file-uploads.controller.ts
Labels: documentation⚡️기능개선, enhancement💻기능추가

#79 TIL-61 Create Category API 구현
  src/src/ExceptionFilters/Errors/Categories/Category.error.ts
  src/src/ExceptionFilters/Errors/Comments/Comment.error.ts
  src/src/ExceptionFilters/Errors/ErrorHandlerNotFound.error.ts
  src/src/ExceptionFilters/Errors/Posts/Post.error.ts
  src/src/ExceptionFilters/Errors/Tags/Tag.error.ts
  src/src/ExceptionFilters/Errors/UserBlogCustomization/UserBlogCustomization.Error.ts
  src/src/ExceptionFilters/Errors/Users/User.error.ts
  src/src/ExceptionFilters/HttpException.filter.ts
  src/src/app.module.ts
  src/src/auth/auth.controller.ts
  src/src/categories/categories.controller.spec.ts
  src/src/categories/categories.controller.ts
  src/src/categories/categories.module.ts
  src/src/categories/categories.service.spec.ts
  src/src/categories/categories.service.ts
  src/src/categories/dto/Categories.Create.DTO.ts
  src/src/comments/comments.controller.ts
  src/src/entities/Category.ts
  src/src/entities/Tags.ts
  src/src/file-uploads/file-uploads.controller.ts
  src/src/file-uploads/file-uploads.service.ts
  src/src/main.ts
  src/src/posts/posts.controller.ts
  src/src/posts/posts.service.ts
  src/src/repositories/categories.repository.ts
  src/src/repositories/tags.repository.ts
  src/src/tags/dto/Tags.Create.DTO.ts
  src/src/tags/tags.controller.spec.ts
  src/src/tags/tags.controller.ts
  src/src/tags/tags.module.ts
  src/src/tags/tags.service.spec.ts
  src/src/tags/tags.service.ts
  src/src/user-blog-customization/user-blog-customization.controller.ts
Labels: enhancement💻기능추가

#81 Til 100 담당 컨트롤러 버그 수정
  src/src/file-uploads/file-uploads.controller.ts
  src/src/posts/posts.controller.ts
Labels: bug🛠버그

#82 Auth UserStats -> UserInfo로 이름을 변경합니다.
  src/src/auth/auth.controller.ts
  src/src/auth/decorators/userInfo.decorator.ts
  src/src/comments/comments.controller.ts
  src/src/user-blog-customization/user-blog-customization.controller.ts
Labels: documentation⚡️기능개선

#83 Add Global ValidationPipe
  src/package-lock.json
  src/package.json
  src/src/main.ts
Labels: enhancement💻기능추가

#84 Add Post Validation
  src/src/entities/Posts.ts
  src/src/posts/posts.controller.ts
Labels: documentation⚡️기능개선

#85 TIl-115 logout 리다이렉트 방법 변경
  src/src/auth/auth.controller.ts
Labels: documentation⚡️기능개선

#86 Modify postDetail Service
  src/src/posts/dto/Services/GetPostDetail.DTO.ts
  src/src/posts/posts.service.ts
Labels: documentation⚡️기능개선

#88 Modify getPostsFoundByMemberId Category Join
  src/src/posts/posts.service.ts
Labels: documentation⚡️기능개선

#89 Add getMostLikedPosts
  src/src/ExceptionFilters/Errors/Posts/Post.error.ts
  src/src/posts/dto/Services/MostLikedPost.DTO.ts
  src/src/posts/posts.controller.ts
  src/src/posts/posts.service.ts
Labels: enhancement💻기능추가

#90 TIL-136 태그 검색 기능 추가
  src/package-lock.json
  src/package.json
  src/src/ExceptionFilters/Errors/Tags/Tag.error.ts
  src/src/auth/auth.controller.ts
  src/src/tags/tags.controller.ts
  src/src/tags/tags.service.ts
  src/src/users/users.service.ts
  src/src/utilities/hungul.ts
Labels: enhancement💻기능추가

#91 TIL-136 카테고리 검색 기능 추가
  .vscode/launch.json
  fn_choSearch.sql
  package-lock.json
  src/src/ExceptionFilters/Errors/Categories/Category.error.ts
  src/src/ExceptionFilters/Errors/Tags/Tag.error.ts
  src/src/categories/categories.controller.ts
  src/src/categories/categories.service.ts
  src/src/tags/tags.controller.ts
Labels: enhancement💻기능추가

#92 fix: 태그 검색 시 결과 값 태그 엔티티 전체 반환하도록 수정
  src/src/tags/tags.service.ts
Labels: bug🛠버그

#93 TIL-60 postsTags 만들기 & 초성 검색 수정
  docker/mysql/mysql-init-files/fn_choSearch.sql
  docker/mysql/mysql-init-files/init.sql
  src/src/ExceptionFilters/Errors/Posts/Post.error.ts
  src/src/categories/categories.service.ts
  src/src/posts/dto/Services/CreatePostTags.DTO.ts
  src/src/posts/posts.controller.ts
  src/src/posts/posts.module.ts
  src/src/posts/posts.service.ts
  src/src/repositories/tags.repository.ts
  src/src/tags/tags.service.ts
  src/src/utilities/compare.array.utility.ts
  src/src/utilities/hungul.ts
Labels: bug🛠버그, enhancement💻기능추가

#94 feat: pinned repository 등록 기능 추가
  src/src/ExceptionFilters/Errors/PinnedRepositories/PinnedRepositories.error.ts
  src/src/app.module.ts
  src/src/pinned-repositories/dto/CreatePinnedRepositories.DTO.ts
  src/src/pinned-repositories/pinned-repositories.controller.spec.ts
  src/src/pinned-repositories/pinned-repositories.controller.ts
  src/src/pinned-repositories/pinned-repositories.module.ts
  src/src/pinned-repositories/pinned-repositories.service.spec.ts
  src/src/pinned-repositories/pinned-repositories.service.ts
Labels: enhancement💻기능추가

#97 fix: 초성 검색 sql 함수 수정
  docker/mysql/mysql-init-files/fn_choSearch.sql
Labels: bug🛠버그
