Repository argon1025/TILog-server, pull requests merged in 2022-01, with the labels that each got.

#132 Til 181 페이징 DESC 정렬시 오류 수정, post.controller 생성, 수정시 응답 데이터 추가
  src/src/posts/posts.controller.ts
  src/src/repositories/posts.repository.ts
Labels: bug🛠버그, documentation⚡️기능개선

#133 Til 187
  src/src/ExceptionFilters/Errors/Auth/Auth.error.ts
  src/src/ExceptionFilters/Errors/Posts/Post.error.ts
  src/src/posts/posts.controller.ts
  src/src/posts/posts.service.ts
Labels: documentation⚡️기능개선

#137 Add Postdetail 좋아요, 조회수 로직 추가
  src/package-lock.json
  src/package.json
  src/src/posts/dto/Services/GetPostDetail.DTO.ts
  src/src/posts/posts.controller.ts
  src/src/posts/posts.service.ts
  src/src/repositories/postViews.repository.ts
  src/src/repositories/posts.repository.ts
Labels: documentation⚡️기능개선, enhancement💻기능추가

#139 캐싱 서비스, 트랜딩 리스트 리팩터링
  src/package-lock.json
  src/package.json
  src/src/app.module.ts
  src/src/cache-manager/cache-manager.module.ts
  src/src/cache-manager/cache-manager.service.spec.ts
  src/src/cache-manager/cache-manager.service.ts
  src/src/main.ts
  src/src/posts/posts.controller.ts
  src/src/posts/posts.module.ts
  src/src/posts/posts.service.ts
  src/src/repositories/posts.repository.ts
Labels: documentation⚡️기능개선, enhancement💻기능추가

#140 Til 212 에러 로깅 큐 추가
  src/package-lock.json
  src/package.json
  src/src/ExceptionFilters/HttpException.filter.ts
  src/src/app.module.ts
  src/src/main.ts
  src/src/task-manager/logging.processor.ts
  src/src/task-manager/task-manager.module.ts
  src/src/task-manager/task-manager.service.ts
Labels: enhancement💻기능추가

#148 hotfix comment를 읽을수없는 에러
  src/src/comments/comments.service.ts
Labels: bug🛠버그

#150 쿼리빌더 Update 별칭 제거
  src/src/posts/posts.service.ts
  src/src/repositories/PostLikes.repository.ts
Labels: bug🛠버그

#151 포스트 내용 제한 완화
  src/src/entities/Posts.ts
  src/src/main.ts
  src/src/posts/posts.service.ts
Labels: documentation⚡️기능개선, enhancement💻기능추가

#153 HotFix ONLY_PUBLIC_POST
  src/src/posts/posts.service.ts
Labels: bug🛠버그

#154 Add Posts 테이블 인덱스
  docker/mysql/mysql-init-files/init.sql
Labels: documentation⚡️기능개선
